### PR TITLE
Unify Dockerfiles for aarch64 and x86_64

### PR DESCRIPTION
**Pull request by MrXinWang**
Referencing [issue#3](https://github.com/rust-vmm/rust-vmm-container/issues/3), propose a PR to unify Dockerfiles for x86_64 and aarch64. This unified docker image can serve as the base image.

Signed-off-by: Henry Wang <<henry.wang@arm.com>>

### CODE REVIEW

**Comment by MrXinWang** [comment]
Hi @aghecenco ! Thanks for the suggestions. I have updated the README.md and removed the weird commit message autogenerated by the commit message hook. Please review them again. Thanks.

**Comment by andreeaflorescu** [comment]
@MrXinWang I tried to build a new container image using the new Dockerfile and it fails with the following error when installing kcov:
```
Scanning dependencies of target kcov_system_lib
[  8%] Building CXX object src/CMakeFiles/kcov_system_lib.dir/engines/system-mode-binary-lib.cc.o
[  9%] Building CXX object src/CMakeFiles/kcov_system_lib.dir/utils.cc.o
[ 10%] Building CXX object src/CMakeFiles/kcov_system_lib.dir/system-mode/registration.cc.o
[ 12%] Linking CXX shared library libkcov_system_lib.so
[ 12%] Built target kcov_system_lib
[ 13%] Generating version.c
[ 14%] Generating library.cc
/usr/bin/env: 'python3': No such file or directory
src/CMakeFiles/kcov.dir/build.make:62: recipe for target 'src/library.cc' failed
make[2]: *** [src/library.cc] Error 127
make[2]: *** Deleting file 'src/library.cc'
CMakeFiles/Makefile2:207: recipe for target 'src/CMakeFiles/kcov.dir/all' failed
make[1]: *** [src/CMakeFiles/kcov.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

The problem seems to be that kcov now requires python3 as a dependency. While this is not strictly related to your PR, can you also please update the kcov installation? Something like this should work:
```
# Installing kcov.
# For some strange reason, the command requires python to be installed
RUN apt-get -y install python3
RUN cargo kcov --print-install-kcov-sh | sh
```

**Comment by MrXinWang** [comment]
Hi @andreeaflorescu ! Sorry about the delayed reply, was on a business trip and therefore didn't check my email. I have already changed the code following your instructions, and thanks for pointing it out.

**Comment by andreeaflorescu** [comment]
Thanks @MrXinWang!

**Pull request merged**
